### PR TITLE
Move transactions to a global level

### LINKED ISSUE #28: mysqldump-php generates inconsistent snapshot of the Database!
I originally reported this in `gdpr-dump` repo https://github.com/Smile-SA/gdpr-dump/issues/86 but I traced the bug `mysqldump-php`, I opened a bug at the old repo, as well as this seems more active fork.

When working with large databases, we noticed that generated dump is inconsistent. Some tables will include rows inserted **after the dump** was initiated. This problem became a dealbreaker with bigger databases.

Tracing this further, it turns out that `mysqldump-php` **starts a transaction per [table](https://github.com/ifsnop/mysqldump-php/blob/master/src/Ifsnop/Mysqldump/Mysqldump.php#L1219)** and not for the entire dump process. This is unlike the behavior of the `mysqldump` command.

### PR DESCRIPTION
**Pull request by guvra**
Fixes #28

FYI this was already merged in the original repo with the following commit: https://github.com/ifsnop/mysqldump-php/commit/2d3a43fc0c49f23bf7dee392b0dd1f8c799f89d3

### CODE REVIEW

**Comment by back-2-95** [comment]
Hello, could you update your branch with the latest main changes (GHA runners) so we can complete those tests ^^

**Comment by guvra** [comment]
> Hello, could you update your branch with the latest main changes (GHA runners) so we can complete those tests ^^

Done :+1:

**Comment by back-2-95** [comment]
Tests pass and as it was merged to original repo also, I'll merge 👍

**Comment by guvra** [comment]
Hi @back-2-95

I see that the latest release is from January and does not include this fix, would it be possible to release a new version of the package?

**Comment by back-2-95** [comment]
Hi @guvra ! I made a new release https://github.com/druidfi/mysqldump-php/releases/tag/1.0.3

**Pull request merged**
