### PR TITLE
Fix #17 - Virtual Blob Columns were not treated as virtual

### LINKED ISSUE #17: Virtual columns cause side effects (complete inserts switched on) and break gdpr-dump of Shopware 6
When virtual columns appear during dumping, complete-inserts are switched on.

With generated columns it causes also a "Column count doesn't match value count"

See here for more details: https://github.com/Smile-SA/gdpr-dump/issues/78

### PR DESCRIPTION
**Pull request by amenk**
* Virtual columns have a special handling
* If there are such columns, we need to switch to complete inserts for the table and omit the virtual values in the INSERTs
* If a column is virtual and blob, due to an error in the if-priority it was no longer treated as virtual
* Additionally the complete-insert switching also affected consequent tables, this PR isolates this to affect only the current table with the virtual columns

### CODE REVIEW

**Comment by back-2-95** [comment]
Tests pass.

So this is only for 5.7 ?

Could you provide the background on the PR description what is done here and why.

**Comment by amenk** [comment]
Actually I am not sure if it is only for 5.7 -- should probably apply to all versions with virtual fields

**Comment by back-2-95** [comment]
Aah, I just read the diffs and there was 5 and 7 used for ifs so I assumed.

**Comment by amenk** [comment]
okay, looks like my tests just would run for >= 5.7 but I think that is okay, I copied that from the other tests with virtual columns

**Comment by back-2-95** [comment]
@amenk It's now merged. I'm not gonna do a release yet until I have tested this in real projects.

**Comment by amenk** [comment]
@back-2-95 okay, cool, keep me posted :-)

**Comment by amenk** [comment]
Did you have a chance to test in a real project, yet?
Also now with the PHP8.2 support a tagged release would be awesome :-)

See also https://github.com/Smile-SA/gdpr-dump/pull/79

**Comment by back-2-95** [comment]
Hi @amenk not yet but I created a patch release https://github.com/druidfi/mysqldump-php/releases/tag/1.0.2

**Pull request merged**
